### ISSUE TITLE
Add "Home internet"

### ISSUE THREAD

**Issue by Levante75** [geertmeersman/mobile_vikings#100]
Nice integration thank you!
I have also internet through Mobile Vikings. Is it possible to add this service "Internet Thuis"?

![image](https://github.com/geertmeersman/mobile_vikings/assets/63196199/39ebe738-114d-472f-b893-1b7d36d29ffb)

**Comment by geertmeersman** [comment]
Hi, is it possible to join me on discord? This would ease exchanging and fetching the necessary data in order to complete the API  calls for the integration

https://discord.com/invite/9w6UAsutdJ

**Comment by Levante75** [comment]
Done!
