### ISSUE TITLE
Suggestions from MV dev team

### ISSUE THREAD

**Issue by Kjoep** [geertmeersman/mobile_vikings#125]
Hey there! It's your pals at Mobile Vikings! 👋  Just dropping by to let you know that we noticed some funky patterns in our traffic log, and guess what? We're totally digging your project!

Now, we've got a couple of tips, or should we say, requests 😉

Our API is your playground, no need to reverse engineer anything.  It's documented at https://uwa.mobilevikings.be/.  Drop us a line at [api@mobilevikings.be](mailto:api@mobilevikings.be) for a key. Sure, you might already have one, but a dedicated one would be beter. It helps us figure out where the love is coming from!

Oh, and not need to use a fake user agent string. Just call yourself ‘home assistant' or something. As long as it's not blank, we're cool. We like transparency and might even slide into your DM’s if we spot a bug. 😉

If at all possible, reuse your auth tokens. If it's expired you can use the refresh token mechanism to get a new one. You can save off some requests and it helps to keep our token tables tidy. 

Happy coding, and don't hesitate to reach out if you need anything!

Cheers, 
The MV dev team 🚀

**Comment by geertmeersman** [comment]
Just saw the API, clear enough :-) Thanks for pointing it out! Request for the key will arrive soon

**Comment by Kjoep** [comment]
Yup.  Just one key will do.  Thanks!

**Comment by geertmeersman** [comment]
No need to set it stale, WIP

**Comment by geertmeersman** [comment]
@Kjoep implemented in PR #164 , release https://github.com/geertmeersman/mobile_vikings/releases/tag/v1.0.0
