### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by dc911x** [geertmeersman/mobile_vikings#62]
**Describe the bug**
Integration not working any more, remove and readding account gives service unavailable.

**To Reproduce**

Adding an account gives you Service unavailable

![afbeelding](https://github.com/geertmeersman/mobile_vikings/assets/49455017/b0a0182a-08ad-4069-9a00-4cf2e64da4ec)

**Additional context**
I deleted my entries but I believe this behaviour started on 13/09

**Comment by geertmeersman** [comment]
Hi Jelle, possible to activate debug on the integration and provide me with the logs? At my side it is still working fine

**Comment by dc911x** [comment]
> Hi Jelle, possible to activate debug on the integration and provide me with the logs? At my side it is still working fine

Just enabled debug and guess what... I could login...
![afbeelding](https://github.com/geertmeersman/mobile_vikings/assets/49455017/76937f65-54d8-4492-8ed6-cbe54e8a0071)

Anyway I'll let debug on in case it happens again. 

PS: I used bitwarden to fill in the password because it seems giving an incorrect password also gives the "service unavailable" message. 

Thanks for taking the time trying to help me.

**Comment by geertmeersman** [comment]
I'll indeed add the  badcredentials exception :-) sorry for the confusion

**Comment by geertmeersman** [comment]
![image](https://github.com/geertmeersman/mobile_vikings/assets/1844091/3d9b1e11-137c-4c0b-a372-a808fc657a5b)
