### ISSUE TITLE
Internet Sensors

### ISSUE THREAD

**Issue by KRi570F** [geertmeersman/mobile_vikings#65]
Since a few months Mobile Vikings now offers Internet also. Can you please add these sensors also?

**Comment by geertmeersman** [comment]
Hi Kristof, sure. Could you join on Discord, as I will probably need some data (I don't have the internet offer included, so I don't have the data :-)

https://discord.gg/9w6UAsutdJ

**Comment by geertmeersman** [comment]
@KRi570F , possible to  share some debug data? Like  API response  on the internet calls?
