### ISSUE TITLE
Remaining credit when monthly "bundle" has expired

### ISSUE THREAD

**Issue by bavala3010** [geertmeersman/mobile_vikings#66]
Hi, is it possible to add a sensor that shows the value of the remaining credit when the monthly bundle has expired?

Context: with a prepaid account, you can charge your account with a credit that lasts for 1 month. Eg. you charge 15 euro at the beginning of the month. During the month, you use internet and make a few calls. If you stay within the limits of the monthly use, there is no additional cost and by the end of the month, you will still have the initial 15 euro.
When the monthly bundle has expired, you can use these 15 euro to use internet (x €/MB and x €/minute). Of course, it will only take a few days (sometimes a week, depending on your usuage) before that credit is totally used.

By having a sensor that shows the remaining credit, you could have a precise when you really need to recharge and pay for another monthly bundle.

Thanks for considering this change request.

**Comment by geertmeersman** [comment]
Hi, sure I can add it. But then I will need api data / possible for you to join on Discord so we can exchange some information that will help  me out in building it?

**Comment by tjorim** [comment]
I sent you a message on Discord as well.

**Comment by geertmeersman** [comment]
The credit is already available as an extra attribute in the out of bundle sensor, but I will add it as a separate sensor :-)
